In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os,sys
import glob,shutil
import json

import cv2
import numpy as np
import matplotlib.pyplot as plt

## image splitter

In [14]:
from picture_splitter import ImageSplitter 

In [67]:
path_images = r"C:\Users\admin\alex_gitrepos\temp\imagesplitter\dataset\images"
path_labels = r"C:\Users\admin\alex_gitrepos\temp\imagesplitter\dataset\labels"
path_out    = r"C:\Users\admin\alex_gitrepos\temp\imagesplitter\outputs"
imgsplitter = ImageSplitter(path_images, path_labels, path_out)

In [68]:
imgsplitter.process()

bboxes:[[   2  715  527   62   60]
 [   2  792  482   52   54]
 [   2  873  433   74   58]
 [   2 1008  421   56   46]], img_w:1056
bboxes:[[  2 144 421  56  46]
 [  1 207 526  20  46]
 [  2 258 227  60  48]
 [  2 297 144  42  46]
 [  2 339 182  48  38]
 [  2 358 101  54  42]
 [  2 413 202  50  48]], img_w:1056
bboxes:[[  2 513 184  74  68]
 [  2 715  41  62  60]], img_w:1056
bboxes:[[  1 207  40  20  46]], img_w:1056


In [ ]:
imgsplitter.file_labels

In [59]:
a = [1.0,2,3]
a = np.array(a)
"{0:d} {1:.2f} {2}".format(int(a[0]), a[1], a[2])

'1 2.00 3.0'

In [65]:
a = np.random.randn(2,2)
a

array([[ 1.12943903, -0.69958767],
       [-0.32150247, -1.43688213]])

In [66]:
a[:,[0,1]]

array([[ 1.12943903, -0.69958767],
       [-0.32150247, -1.43688213]])

## map calculator

In [ ]:
from map_calculator import *

In [ ]:
path_mAP = r"H:\deepLearning\dataset\visdrone_mAP\map_truckerror"
mc = MAP_Calculator(path_mAP)

In [ ]:
mc.class_names

In [ ]:
mc.gt_classes_idx

In [ ]:
mc.gt_counter_images_per_class

In [ ]:
mc.gt_counter_per_class

In [ ]:
mc.dr_counter_per_class

In [ ]:
mc.ap_calculate()

In [ ]:
mc.draw_ground_truth_info()

In [ ]:
mc.draw_map()

In [ ]:
mc.draw_detection_results_info()